import type { Linter } from 'eslint';

const reactConfig: Linter.Config = {
  rules: {
    '@stylistic/jsx-closing-bracket-location': [ 'error', 'line-aligned' ],
    '@stylistic/jsx-curly-newline': [ 'error', {
      multiline: 'consistent',
      singleline: 'consistent',
    } ],
    '@stylistic/jsx-curly-spacing': [ 'error', {
      children: true,
      when: 'always',
    } ],
    '@stylistic/jsx-first-prop-new-line': [ 'error', 'multiline-multiprop' ],
    'class-methods-use-this': [ 'error', {
      exceptMethods: [
        'render',
        'getInitialState',
        'getDefaultProps',
        'getChildContext',
        'componentDidMount',
        'shouldComponentUpdate',
        'componentDidUpdate',
        'componentWillUnmount',
        'componentDidCatch',
        'getSnapshotBeforeUpdate',
      ],
    } ],
    'react/button-has-type': [ 'error', {
      button: true,
      reset: false,
      submit: true,
    } ],
    'react/default-props-match-prop-types': [ 'error', { allowRequiredDefaults: false } ],
    'react/destructuring-assignment': [ 'error', 'always' ],
    'react/forbid-foreign-prop-types': [ 'warn', { allowInPropTypes: true } ],
    'react/forbid-prop-types': [ 'error', {
      checkChildContextTypes: true,
      checkContextTypes: true,
      forbid: [ 'any', 'array', 'object' ],
    } ],
    'react/function-component-definition': [ 'error', {
      namedComponents: [ 'function-declaration', 'function-expression' ],
      unnamedComponents: 'function-expression',
    } ],
    'react/jsx-boolean-value': [ 'error', 'never', { always: [] } ],
    'react/jsx-filename-extension': [ 'error', { extensions: [ '.jsx', '.tsx' ] } ],
    'react/jsx-fragments': [ 'error', 'syntax' ],
    'react/jsx-no-bind': [ 'error', {
      allowArrowFunctions: true,
      allowBind: false,
      allowFunctions: false,
      ignoreDOMComponents: true,
      ignoreRefs: true,
    } ],
    'react/jsx-no-constructed-context-values': 'error',
    'react/jsx-no-duplicate-props': [ 'error', { ignoreCase: true } ],
    'react/jsx-no-script-url': [ 'error', [
      {
        name: 'Link',
        props: [ 'to' ],
      },
    ] ],
    'react/jsx-no-undef': 'error',
    'react/jsx-no-useless-fragment': 'error',
    'react/jsx-pascal-case': [ 'error', {
      allowAllCaps: true,
      ignore: [],
    } ],
    'react/jsx-sort-props': [ 'error', {
      ignoreCase: true,
      reservedFirst: false,
    } ],
    'react/jsx-uses-vars': 'error',
    'react/no-access-state-in-setstate': 'error',
    'react/no-array-index-key': 'error',
    'react/no-arrow-function-lifecycle': 'error',
    'react/no-children-prop': 'error',
    'react/no-danger': 'warn',
    'react/no-danger-with-children': 'error',
    'react/no-deprecated': [ 'error' ],
    'react/no-did-update-set-state': 'error',
    'react/no-find-dom-node': 'error',
    'react/no-invalid-html-attribute': 'error',
    'react/no-is-mounted': 'error',
    'react/no-namespace': 'error',
    'react/no-redundant-should-component-update': 'error',
    'react/no-render-return-value': 'error',
    'react/no-string-refs': 'error',
    'react/no-this-in-sfc': 'error',
    'react/no-typos': 'error',
    'react/no-unescaped-entities': 'error',
    'react/no-unstable-nested-components': 'error',
    'react/no-unused-class-component-methods': 'error',
    'react/no-unused-prop-types': [ 'error', {
      customValidators: [
      ],
      skipShapeProps: true,
    } ],
    'react/no-unused-state': 'error',
    'react/no-will-update-set-state': 'error',
    'react/prefer-exact-props': 'error',
    'react/self-closing-comp': 'error',
    'react/sort-comp': [ 'error', {
      groups: {
        lifecycle: [
          'displayName',
          'propTypes',
          'contextTypes',
          'childContextTypes',
          'mixins',
          'statics',
          'defaultProps',
          'constructor',
          'getDefaultProps',
          'getInitialState',
          'state',
          'getChildContext',
          'getDerivedStateFromProps',
          'componentDidMount',
          'shouldComponentUpdate',
          'getSnapshotBeforeUpdate',
          'componentDidUpdate',
          'componentDidCatch',
          'componentWillUnmount',
        ],
        rendering: [
          '/^render.+$/',
          'render',
        ],
      },
      order: [
        'static-variables',
        'static-methods',
        'instance-variables',
        'lifecycle',
        '/^handle.+$/',
        '/^on.+$/',
        'getters',
        'setters',
        '/^(get|set)(?!(InitialState$|DefaultProps$|ChildContext$)).+$/',
        'instance-methods',
        'everything-else',
        'rendering',
      ],
    } ],
    'react/state-in-constructor': [ 'error', 'always' ],
    'react/static-property-placement': [ 'error', 'property assignment' ],
    'react/style-prop-object': 'error',
    'react/void-dom-elements-no-children': 'error',
  },
  settings: {
    react: {
      pragma: 'React',
      version: 'detect',
    },
  },
};

export default reactConfig;
